# Generated by Django 3.0.2 on 2020-01-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='short_url',
            new_name='short_urls',
        ),
    ]
