# Generated by Django 3.0.2 on 2020-01-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200114_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='short_urls',
            old_name='long_url',
            new_name='url',
        ),
    ]
